# Copyright 2017 IBM Corp.
#
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: v2.0

location:
    time_zone: UTC
    data_center: dataeast
    racks:
        - label: rack_1
          room: room33
          row: row1
          cell: 42

globals:
    introspection: False
    switch_mode_mgmt: active
    dhcp_lease_time: 15m

deployer:
    gateway: true
    networks:
        mgmt:
            - device: enP1p10s0f0
              interface_ipaddr: 192.168.32.95
              prefix: 24
        client:
            - device: enP1p10s0f0
              type: pxe
              container_ipaddr: 192.168.12.2
              bridge_ipaddr: 192.168.12.3
              prefix: 24
              vlan: 12
            - device: enP1p10s0f0
              type: ipmi
              container_ipaddr: 192.168.11.2
              bridge_ipaddr: 192.168.11.3
              prefix: 24
              vlan: 11

switches:
    mgmt:
        - label: mgmt_1_1
          class: lenovo
          hostname: mymgmt_1_1
          userid: admin
          password: 
          ssh_key: <path1>
          rack_id: rack_1
          rack_eia: 33
          interfaces:
              - type: outband
                ipaddr: 192.168.32.20
          links:
              - target: deployer
                ports: 18
              - target: data_1_1
                ports: 45

    data:
        - label: data_1_1
          class: mellanox
          hostname: mydata_1
          userid: admin
          password: 
          ssh_key: <path2>
          rack_id: rack_1
          rack_eia: 34
          interfaces:
              - type: outband
                ipaddr: 192.168.32.25
                port: mgmt0
          links:
              - target: mgmt_1_1
                ipaddr: 192.168.5.31
                ports:
                    - mgmt0

interfaces:
    - label: pxe_ifc
      description: pxe interface
      iface: eth15
      method: dhcp

    - label: bond1_interface1
      description: manual bond ifc 1
      iface: eth1
      #mtu: 9000
      method: manual
      bond_master: bond1
      #bond_primary: eth1

    - label: bond1_interface2
      description: manual bond ifc 2
      iface: eth2
      #mtu: 9000
      method: manual
      bond_master: bond1

    - label: bond1_mstr
      description: bond interface 1
      iface: bond1
      method: static
      address_list:
          - 9.3.89.34
          - 9.3.89.36
      netmask: 255.255.255.0
      gateway: 9.3.89.1
      dns_nameservers: 9.3.1.200 9.0.128.50
      #mtu: 9000
      bond_mode: 802.3ad
      bond_miimon: 100
      bond_slaves: eth1 eth2

networks:
    - label: nets
      interfaces:
          - bond1_mstr

node_templates:
    - label: power_servers
      ipmi:
          userid: ADMIN
          password: 
      os:
          hostname_prefix: server
          profile: ubuntu-16.04.4-server-ppc64el
#          install_device: /dev/sdj
          install_device: /dev/disk/by-path/pci-0000:01:00.0-sas-phy0-lun-0
          users:
              - name: user1
                password: 
#      networks:
      interfaces:
          - bond1_interface1
          - bond1_interface2
          - bond1_mstr

      # Each host has one network interface for each of these ports and
      # these port numbers represent the switch port number to which the host
      # interface is physically cabled.
      # To add or remove hosts for this node_template you add or remove
      # switch port numbers to these ports.
      physical_interfaces:
          ipmi:
              - switch: mgmt_1_1
                ports:
                    - 12
                    - 10
          pxe:
              - switch: mgmt_1_1
                interface: pxe_ifc
                rename: false
                ports:
                    - 11
                    - 9
          data:
              - switch: data_1_1
                interface: bond1_interface1
                rename: true
                ports:
                    - 33
                    - 9

              - switch: data_1_1
                interface: bond1_interface2
                rename: true
                ports:
                    - 34
                    - 10

software_bootstrap:
    - hosts: server-1
      command: |
        set -e
        apt-get update
        apt install git -y
        rm -rf ICP-install/
        git clone https://github.com/open-power-ref-design/ICP-install.git
        cd ICP-install/
        chmod +x icp-install.sh
        ./icp-install.sh 
    - hosts: all
      command: touch xyz.txt

# Additional key/value pairs are not processed by Genesis, but are copied into
# the inventory.yml file and made available to post-Genesis scripts and/or
# playbooks.
