software_bootstrap:
    - hosts: server-1
      command: |
        set -e
        apt-get update
        apt install git -y
        rm -rf ICP-POWER-Up/
        git clone https://github.com/mtarsel/ICP-POWER-Up.git
        cd ICP-POWER-Up/
        chmod +x icp-install.sh
        ./icp-install.sh
    - hosts: all
      command: touch xyz.txt
