software_bootstrap:
    - hosts: server-1
      command: |
        set -e

#RHEL install
        if [ -f /etc/redhat-release ]; then
           yum update
           #TODO this assumes we have proper channels enabled to install docker!!
           wget https://github.com/open-power-ref-design/ICP-install/blob/master/scripts/icp-install-rhel.sh
           chmod +x icp-install-rhel.sh
           ./icp-install-rhel.sh
        fi
       
#Ubuntu install 
        if [ -f /etc/lsb-release ]; then
           wget https://github.com/open-power-ref-design/ICP-install/blob/master/scripts/icp-install-debian.sh
           wget https://github.com/open-power-ref-design/ICP-install/blob/master/scripts/install_docker.sh
           chmod +x icp-install-debian.sh
           chmod +x install_docker.sh
           ./icp-install-debian.sh 
        fi
