software_bootstrap:
    - hosts: server-1
      command: |
        set -e

#RHEL install
        if [ -f /etc/redhat-release ]; then
           yum update
           wget https://raw.githubusercontent.com/open-power-ref-design/ICP-install/master/scripts/icp-install-rhel.sh
           chmod +x icp-install-rhel.sh
           ./icp-install-rhel.sh {{ icp-version }}
        fi
       
#Ubuntu install 
        if [ -f /etc/lsb-release ]; then
           wget https://raw.githubusercontent.com/open-power-ref-design/ICP-install/master/scripts/icp-install-debian.sh 
           wget https://raw.githubusercontent.com/open-power-ref-design/ICP-install/master/scripts/install_docker.sh
           chmod +x icp-install-debian.sh
           chmod +x install_docker.sh
           ./icp-install-debian.sh {{ icp-version }} 
        fi
