software_bootstrap:
    - hosts: server-1
      command: |
        set -e
        apt-get update
        apt install git -y
        rm -rf ICP-install/
        git clone https://github.com/open-power-ref-design/ICP-install.git
        cd ICP-install/
        chmod +x icp-install.sh
        ./icp-install.sh
